### ISSUE TITLE
Missing go import path config

### ISSUE THREAD

**Issue by cdfa** [thought-machine/please-examples#10]
I believe you are missing the following lines in your `.plzconfig`:
```
[go]
importpath = github.com/thought-machine/pleasings
```

Without it, I get the following error on `./pleasew test`
```
Build stopped after 4.79s. 1 target failed:
///pleasings//java/maven:_maven#lib
Error building target ///pleasings//java/maven:_maven#lib: exit status 1
java/maven/main.go, line 20, column 2: can't find import: "github.com/thought-machine/pleasings/java/maven/maven"
```

I found this bit of config in the pleasings repo. You should really add a general getting started guide for gRPC with Please.

**Comment by Tatskaari** [comment]
Sorry for the _very_ slow reply here.

I think this has been fixed now. Unfortunately the `.plzconfig` won't be respected by the host repo when subrepo'ing pleasings so we have to set it with `package()` per BUILD file.
